# Generated by Django 4.2.16 on 2026-03-29 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='mesas.grupomesas'),
        ),
    ]
