# Generated by Django 5.2.13 on 2026-04-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_grupomesas_mesa_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomesas',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
