# Generated by Django 5.2.9 on 2026-05-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0004_add_nombre_to_grupomesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='mesaNombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
