# Generated by Django 4.2.21 on 2025-07-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_productomenu_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productomenu',
            old_name='imagenUrl',
            new_name='imagen',
        ),
    ]
