# Generated by Django 4.2.21 on 2025-07-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_imagenurl_productomenu_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productomenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
