# Generated by Django 4.2.23 on 2025-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_categoriamenu_id_alter_productomenu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomenu',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
