# Generated by Django 4.2.23 on 2025-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_productomenu_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomenu',
            name='tiempoPreparacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
