# Generated by Django 4.2.23 on 2025-07-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_productomenu_tiempopreparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomenu',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
