# Generated by Django 4.2.23 on 2025-08-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_productomenu_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamenu',
            name='ordenMenu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
