# Generated by Django 5.2 on 2025-11-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_categoriamenu_ordenmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomenu',
            name='mostrarEnListado',
            field=models.BooleanField(default=True),
        ),
    ]
