# Generated by Django 5.2.9 on 2026-02-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_productomenu_mostrarenlistado'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaMetricas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
