# Generated by Django 5.2.9 on 2026-02-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_categoriametricas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriametricas',
            name='nombreCategoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
