# Generated by Django 5.2.9 on 2026-02-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_categoriametricas_nombrecategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomenu',
            name='categoriaMetrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='menu.categoriametricas'),
        ),
    ]
