# Generated by Django 4.2.23 on 2025-07-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0002_alter_mesa_id'),
        ('menu', '0004_alter_categoriamenu_id_alter_productomenu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreOrden', models.CharField(default='ORDEN_DEFAULT', max_length=100, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='proceso', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idMesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.productomenu')),
            ],
        ),
    ]
