# Generated by Django 4.2.23 on 2025-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombreOrden',
            field=models.CharField(max_length=100),
        ),
    ]
