# Generated by Django 4.2.23 on 2025-08-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_pedido_nombreorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='status',
            field=models.CharField(choices=[('proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='proceso', max_length=20),
        ),
    ]
