# Generated by Django 4.2.23 on 2025-08-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_detallepedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
    ]
