# Generated by Django 4.2.23 on 2025-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_remove_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='proceso', max_length=20),
        ),
    ]
