# Generated by Django 5.2 on 2025-11-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='mostrarEnListado',
            field=models.BooleanField(default=True),
        ),
    ]
