# Generated by Django 5.2 on 2025-11-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_detallepedido_mostrarenlistado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='mostrarEnListado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='mostrarEnListado',
            field=models.BooleanField(default=True),
        ),
    ]
