# Generated by Django 5.2 on 2025-11-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_remove_detallepedido_mostrarenlistado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mostrarEnListado',
        ),
    ]
