# Generated by Django 4.2.28 on 2026-02-21 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_remove_pedido_mostrarenlistado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
