# Generated by Django 5.2.9 on 2026-03-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_detallepedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
